import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';

import 'model.dart';

class HomeApi extends StatefulWidget {
  const HomeApi({super.key});

  @override
  State<HomeApi> createState() => _HomeApiState();
}

class _HomeApiState extends State<HomeApi> {
  late Future<List<Autogenerated>> myData;

  @override
  void initState() {
    super.initState();
    myData = fetchData();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FutureBuilder<List<Autogenerated>>(
        future: myData,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          } else if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          } else if (snapshot.hasData) {
            final data = snapshot.data!;
            return ListView.builder(
                itemCount: data.length,
                itemBuilder: (context, index) {
                  final item = data[index];
                  return Container(
                    height: 200,
                    color: Colors.greenAccent,
                    padding: const EdgeInsets.symmetric(
                        horizontal: 10, vertical: 10),
                    margin: const EdgeInsets.all(10),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('userId: ${item.userId}'),
                        Text('id: ${item.id}'),
                        Text('title: ${item.title}'),
                        Text('body: ${item.body}')
                      ],
                    ),
                  );
                });
          } else {
            return const Center(child: Text('No data found'));
          }
        },
      ),
    );
  }

  Future<List<Autogenerated>> fetchData() async {
    final response =
        await http.get(Uri.parse('https://jsonplaceholder.typicode.com/posts'));
    print("response is: $response");
    print("response code: ${response.statusCode}");
    if (response.statusCode == 200) {
      final List<dynamic> data = jsonDecode(response.body);
      return data.map((e) => Autogenerated.fromJson(e)).toList();
    } else {
      throw Exception('Failed to load data');
    }
  }
}
